name: Continuous integration

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup GNU Fortran
        uses: modflowpy/install-gfortran-action@v1
      - name: Install test dependencies
        run: |
          pip install -e ".[tests]"
      - name: Test with pytest
        # The flag -s stops pytest from capturing output
        # This is necessary until proper error reporting is implemented by Modflow
        run: |
          pytest -vs --cov=xmipy --cov-report=xml tests/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install lint dependencies
        run: |
          pip install -e ".[lint]"
      - name: Build and check packages
        run: |
          pip install --upgrade build twine
          python -m build
          twine check --strict dist/*
