name: Continuous integration

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [ubuntu-latest, macos-lates, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install system dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo ln -fs /usr/bin/gfortran-9 /usr/local/bin/gfortran
        gfortran --version
    - name: Install system dependencies (macOS)
      if: runner.os == 'macOS'
      run: |  
        gfortran --version
    - name: Install system dependencies (Windows)
      if: runner.os == 'Windows'
      run: |  
        gfortran --version
    - name: Install amipy
      run: |
        pip install .
        pip install https://github.com/modflowpy/pymake/zipball/master
        pip install https://github.com/modflowpy/flopy/zipball/develop
        pip install coveralls nose-timer
    - name: Test with nosetests
      run: |
        nosetests -v --with-id --with-timer -w ./autotest --with-coverage --cover-package=amipy

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install flake8
      run: |
        pip install flake8
    - name: Run Flake8
      run: flake8
