name: Continuous integration

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install and print system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo ln -fs /usr/bin/gfortran-10 /usr/local/bin/gfortran
          gfortran --version
      # Remove as soon as https://github.com/modflowpy/pymake/issues/111 is fixed
      - name: Install numpy
        run: |
          pip install numpy
      - name: Install and print system dependencies (macOS)
        shell: bash
        if: runner.os == 'macOS'
        run: |
          sudo ln -fs /usr/local/bin/gfortran-10 /usr/local/bin/gfortran
          gfortran --version
      - name: Install and print system dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          gfortran --version
      - name: Install test dependencies
        run: |
          pip install -e ".[tests]"
      - name: Test with pytest
        # The flag -s stops pytest from capturing output
        # This is necessary until proper error reporting is implemented by Modflow
        run: |
          pytest -vs --cov=xmipy --cov-report=xml tests/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
      - name: Install lint dependencies
        run: |
          pip install -e ".[lint]"
      - name: Run black
        run: black --check .
      - name: Run isort
        run: isort --check .
      - name: Run mypy
        run: |
          mypy --install-types --non-interactive
          mypy --check --ignore-missing-imports .
