name: Continuous integration

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.pixi-environment }} - ${{ matrix.os }}
    runs-on: "${{ matrix.os }}"
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        pixi-environment: ["py39", "py310", "py311", "py312"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v6
      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.6
        with:
          manifest-path: pyproject.toml
          environments: ${{ matrix.pixi-environment }}
      - name: Install MODFLOW 6
        run: pixi run -e ${{ matrix.pixi-environment }} get-exes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test with pytest
        run: pixi run -e ${{ matrix.pixi-environment }} tests-ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MODFLOW_BIN_PATH: ${{ github.workspace }}/bin
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
